### ISSUE TITLE
ASGI Mode Causes Timeout Errors in Next.js Server-Side Rendering

### ISSUE THREAD

**Issue by neuneed** [QueraTeam/django-nextjs#23]
Hello, I've encountered an issue when trying to integrate django-nextjs into my Django project. The issue arises when using ASGI and channels to run the server.

I have a URL path like so: `url(r'^content', views.nextjs_content, name='content')`, and the associated view function is an asynchronous function:

```
async def nextjs_content(request):
    return await render_nextjs_page(request)
```

Everything works perfectly fine in this setup, including Fast Refresh. However, when I introduce Server-Side Rendering (SSR) into my Next.js page (src/pages/content/[id].tsx), I start to encounter timeout errors. Specifically, my getServerSideProps function times out:

```
export async function getServerSideProps(context) {
    const { id } = context.params
    const url = `content/${id}/`

    try {
        const res = await axiosInstance.get(url)
        return { props: { data: res?.data } }
    } catch (error) {
        return {
            notFound: true,
        }
    }
}
```
The error I get is: AxiosError: timeout of 20000ms exceeded.

Interestingly, if I switch back to WSGI mode using python manage.py runserver --noasgi and add `path("", include("django_nextjs.urls"))` to my URLs, everything works fine. However, in this setup, I lose the benefit of Fast Refresh.

Could you provide some guidance on this? It seems like there might be some issue with the interaction between ASGI, Django-Nextjs, and Next.js's SSR.

Thank you for your time!

**Comment by danialkeimasi** [comment]
Hi,
There is two possibilities:

1. Based on what you explain, it seems like you are requesting the same page in `getServerSideProps` and you are getting to a infinite loop. It is not required to make a request to Django within this function.

2. Since WSGI mode was ok and ASGI mode was not, you may have an sync custom middleware that causes this problem. It will produce a deadlock because of this sequence:
    - User requests to Django to get HTML. in this request sycle, Django requests to Nextjs, and because there is one middleware that is not async capble and there is only one thread, it will wait be blocked and your Django server will not respond to new requests.
    - Nextjs requests to Django in `getServerSideProps` to get data.
    - Django is blocked since it was already waiting for HTML response from Nextjs.

I think the secound one is more likely.

**Comment by neuneed** [comment]
Additional:
I change the `url(r'^content', views.nextjs_content, name='content')` to `path('content/<int:id>', home_views.nextjs_content, name="content")` and `APPEND_SLASH = False` to settings. then get the django error: 
```
server  | WARNING - Application instance <Task pending name='Task-6' coro=<StaticFilesWrapper.__call__() running at /usr/local/lib/python3.10/site-packages/channels/staticfiles.py:44> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.10/asyncio/futures.py:385, Task.task_wakeup()]>> for connection <WebSocketProtocol client=['172.18.0.1', 56292] path=b'/_next/webpack-hmr'> took too long to shut down and was killed.

server  | Not Found: /content/312
server  | WARNING - Not Found: /content/312
server  | HTTP GET /content/312 404 [20.28, 172.18.0.1:56274]
server  | WARNING - HTTP GET /content/312 404 [20.28, 172.18.0.1:56274]

```
The api call for SSR is still timeout.

my requirment.txt versions is: 
```
asgiref==3.5.2
channels==3.0.3
django-nextjs==2.3.0
django==3.2.11
```

Also the information from the log I don't understand is why `172.18.0.1`, shouldn't it be `127.0.0.1`?

**Comment by neuneed** [comment]
> * Django is blocked

1. The api is different with the HTML urls. So that's should be fine.
2. Django must been blocked in the same time waiting for HTML and return an api call. maybe thats why.

let me try this

> If you're using django channels, make sure all your middlewares are [async-capable](https://docs.djangoproject.com/en/dev/topics/http/middleware/#asynchronous-support).

Thank you!

**Comment by neuneed** [comment]
@danialkeimasi After spending some time converting all my middlewares to use `@sync_and_async_middleware` to support [django middleware asynchronous](https://docs.djangoproject.com/en/4.2/topics/http/middleware/#asynchronous-support), I managed to solve the issue!

Cheers!
