### ISSUE TITLE
CSS/JS not loading in production

### ISSUE THREAD

**Issue by LawrenceKU03** [QueraTeam/django-nextjs#25]
Hi when running django in product the css/js doesn't load or show

**Comment by LawrenceKU03** [comment]
One thing i noticed was that in development everything works well only the 404/500 page do not show due to DEBUG=True but when DEBUG=False it only loads the html with no css/js

**Comment by danialkeimasi** [comment]
Hi. This is [typical Django behavior](https://docs.djangoproject.com/en/4.2/howto/static-files/deployment/).

To serve static files in production, you can use a web server such as Nginx. For instructions related to Nextjs's static files, check out our `README.md`: [Setup Next.js URLs (Production Environment)](https://github.com/QueraTeam/django-nextjs#setup-nextjs-urls-production-environment).
